[[ $(uname -s) == "Darwin" ]] && alias chmod='chmod -v' || alias chmod='chmod -cv'
[[ $(uname -s) == "Darwin" ]] && alias chown='chown -v' || alias chown='chown -cv'
alias cp='cp -v'
alias diff='difft'
alias df='duf -hide special'
alias lazydocker='cd $HOME/Projects; lazydocker; cd -'
alias ln='ln -v'
[[ $(uname -s) == "Darwin" ]] && alias ls='ls -G'
alias ls='exa --icons'
alias mv='mv -v'
alias pip='pip3'
alias py='ipython3'
alias python='python3'
alias rm='rm -v'
md() { pandoc "$1" | lynx -stdin; }  # markdown viewer
